ext {
    flatLafVersion = '3.7.2'
    guiceVersion = '5.1.0'
    pf4jVersion = '3.15.0'
    solonAiVersion = '4.0.3'
}

allprojects {
    group = 'com.aresstack.askai.java8'
    version = (findProperty('releaseVersion') ?: '0.1.0').toString()

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}
